services:
  frontend:
    image: node:18-alpine
    container_name: nextjs_app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://localhost:${BACKEND_PORT}"
      NEXT_TELEMETRY_DISABLED: 1
      CI: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "corepack enable pnpm && pnpm install --no-frozen-lockfile && pnpm dev"
    depends_on:
      - backend


  backend:
    build: ./backend
    container_name: fastapi_app
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg16
    container_name: fastapi_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
